### PR TITLE
Submodules + environment variables in compose file

### PR DESCRIPTION
**Pull request by annusingmar**
Adds git submodules for back-end and front-end, environment variables to make config easier

Supersedes #1

### CODE REVIEW

**Review by Goldenbeasty — DISMISSED** [review]
hell

**Review by Goldenbeasty — CHANGES_REQUESTED** [review]
`docker-compose-plugin` does not exist in Debian repositories `docker-compose` should be referenced instead as it is the more common package

**Comment by annusingmar** [comment]
> `docker-compose-plugin` does not exist in Debian repositories `docker-compose` should be referenced instead as it is the more common package

Docker's official installation method is using [their own repositories](https://docs.docker.com/engine/install/debian/), including for Debian - the Debian repos provide an outdated version. `docker-compose-plugin` is the newer (v2) version of the compose tool.
But I agree that it can brought to attention in the README.

**Review by Goldenbeasty — APPROVED** [review]
What the actual fuck is wrong with docker

**Pull request merged**
